version: '3.8'

services:
  php:
    build: .
    container_name: iotti-dev-php
    volumes:
      - ./out:/var/www/html
      - ./config.php:/var/www/config.php
    networks:
      - iotti-network

  nginx:
    image: nginx:alpine
    container_name: iotti-dev-nginx
    ports:
      - "8080:80"
    volumes:
      - ./out:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - iotti-network

networks:
  iotti-network:
    driver: bridge
